[tool.poetry]
name = "focustree"
version = "0.1.0"
description = ""
authors = ["Gabin Marignier <gabin@focustree.app>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
cairo-lang = "0.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
